version: '3'
services:
  postgres:
    image: "postgres"
    env_file:
      - services/postgres/credentials.env
    volumes:
#      - database-data:/var/lib/postgresql/data/
      - ./services/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
  test-postgres:
    image: "postgres"
    env_file:
      - services/postgres/testcredentials.env
    volumes:
#      - database-data-test:/var/lib/postgresql/data/
      - ./services/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5433:5432
#volumes:
#  database-data:
#  database-data-test:

