package com.richard.studies.realtime.models

enum class RealTimeMessageType {
    OFFSIDE, GOAL, YELLOW_CARD, RED_CARD, SUBSTITUTE, OPPORTUNITY, OTHER, FIRST_HALF_START,
    FIRST_HALF_END, SECOND_HALF_START, SECOND_HALF_END, PENALTY
}
